# Welcome to DemonWolf Boilerplate
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in HTML files,
# you will see them access via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the template via {{ site.myvariable }}.
title: "MrDemonWolf"
email: demonwolf@demonwolfdev.com
description: MrDemonWolf is UX Designer, Gamer, Streamer, Youtuber. Freelancer for UX Design and Wordpress site builds. Want a new website for your company or etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mrdemonwolf.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mrdemonwolf

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - mrdemonwolf.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - templates
