#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}
- {title: About, url: '#about'}
- {title: Work, url: 'work'}
- {title: Projects, url: 'projects'}
- {title: Contact, url: '#contact'}

#-------------------------------
# Menu Section

twitchbanner:
  username: mrdemonwolf
  apikey: n9zpqgrbidq5bujz49eilfkf2lvpnly

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@mrdemonwolf'
  type: 'website'
google-analytics: UA-107275871-1

#-------------------------------
# About Section

about:
- Hi, I'm Nathan. I am a Frontend & UI Designer who has a passion for <strong>creating</strong> unique user <strong>experiences</strong>. Since 2012 I have been proudly making the internet a better place, one website at a time. I have had the pleasure to work on a variety of exciting projects involving <strong>WordPress</strong> development, <strong>UI design & front-end development</strong>.
- Currently I’m a contractor for <a href="https://kreynation.com"><strong>KreyNation</strong></a>. I’m also available for Freelance work for any exciting project with tech startups, businesses, entrepreneurs and developers all across the world to create stunning Interfaces and User Experiences. I look forward to hearing from you!

#-------------------------------
# Hero

hero-title: Nathan Henniges is a

hero:
- {name: Streamer}
- {name: YouTuber}
- {name: Front-end Developer}
- {name: UX Designer}
- {name: Gamer}

hero-button:
  title: Contact Me
  url: '#contact'

#-------------------------------
# Examples Section
# Max of 3

examples:
- {title: 'JSL Hub', url: 'jslhub', picture: 'jslhub.png'}
- {title: 'Aishazart', url: 'aishazart', picture: 'aishazart.png'}
- {title: 'Alan Crytex', url: 'alancrytex', picture: 'alancrytex.png'}

#-------------------------------
# Projects Gallery Section
# Filter

projects_gallery-fliter:
- {title: 'All', name: 'all'}
- {title: 'Adobe XD', name: 'adobe-xd'}
- {title: 'HTML', name: 'html'}
- {title: 'Wordpress', name: 'wordpress'}
- {title: 'Jekyll', name: 'jekyll'}

#Make sure to put images in the /images/project/thumbnails folder.
projects_gallery-thumbnails:
- {title: 'Stream Team', fliter: 'adobe-xd', picture: 'stream_team.png', url: 'stream_team'}
- {title: 'Sushi Restaurant', fliter: 'adobe-xd', picture: 'sushi_restaurant.png', url: 'sushi_restaurant'}

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-spotify', color: 'spotify-color', url: 'https://open.spotify.com/user/demonwolf97/'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'http://www.twitter.com/mrdemonwolf'}
- {icon: 'fa-github', color: 'github-color', url: 'https://www.github.com/mrdemonwolf'}
- {icon: 'fa-youtube', color: 'youtube-color', url: 'https://www.youtube.com/mrdemonwolf'}
- {icon: 'fa-twitch', color: 'twitch-color', url: 'https://www.twitch.tv/mrdemonwolf/'}

social-url:
  spotify: https://open.spotify.com/user/demonwolf97
  twitter: http://www.twitter.com/mrdemonwolf
  github: https://www.github.com/mrdemonwolf
  youtube: https://www.youtube.com/mrdemonwolf
  twitch: https://www.twitch.tv/mrdemonwolf

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
