#-------------------------------
# General Site Settings

title: MrDemonWolf
description: UX Designer // Content Maker
email: demonwolf@demonwolfdev.com
#url: https://mrdemonwolf.github.io
url: http://localhost:3000  #Dev URL

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/mrdemonwolf'
  type: 'website'

#-------------------------------
# Google Analytics Section

google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

blurb: >
  **Testing specializes in making things** for human people.
  Most of the things he makes are [test](http://test.com){:target="_blank"},.


#-------------------------------
# Work Section

#-------------------------------
# Clients Section



#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/mrdemonwolf'}
- {icon: 'github', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/mrdemonwolf'}
- {icon: 'youtube', link: 'https://www.youtube.com/mrdemonwolf'}
- {icon: 'twitch', link: 'http://www.twitch.tv/mrdemonwolf/'}
- {icon: 'spotfity', link: 'http://www.twitch.tv/mrdemonwolf/'}