#-------------------------------
# General Site Settings

title: MrDemonWolf
name: MrDemonWolf
description: MrDemonWolf is UX Designer, Gamer, Streamer, Youtuber. Freelancer for UX Design and Wordpress site builds. Want a new website for your company or etc.
email: demonwolf@demonwolfdev.com

#-------------------------------
# Website URL Section

# url: https://mrdemonwolf.me
url: http://192.168.1.2:3000  #Dev URL

#-------------------------------
# Menu Section

menu:
- {title: About, url: '#about'}
- {title: Projects, url: 'projects'}
- {title: Contact, url: '#contact'}

#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/mrdemonwolf'
  type: 'website'

#-------------------------------
# About Section

about: >
  Hello my name is Nathan Henniges. Been fascinated with computers and design as the age of 13. I started working with websites around 2012. I learned a lot since then on how to better use the tools they have been given to me. I hope to work with UX Design in the future.

#-------------------------------
# Hero

hero:
- {name: Streamer}
- {name: YouTuber}
- {name: UX Designer}
- {name: Gamer}

#-------------------------------
# Examples Section
# Make sure  put images in the /img/examples/ folder.
# Also a Max of 3
examples:
- {name: 'JSL Hub', picture: 'jslhub.jpg'}
- {name: 'Aishazart', picture: 'aishazart.jpg'}

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-spotify', color: 'spotify-color', url: 'https://open.spotify.com/user/demonwolf97/'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'http://www.twitter.com/mrdemonwolf'}
- {icon: 'fa-github', color: 'github-color', url: 'https://www.github.com/mrdemonwolf'}
- {icon: 'fa-youtube', color: 'youtube-color', url: 'https://www.youtube.com/mrdemonwolf'}
- {icon: 'fa-twitch', color: 'twitch-color', url: 'https://www.twitch.tv/mrdemonwolf/'}

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
