#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}
- {title: About, url: '#about'}
- {title: Work, url: 'work'}
- {title: Projects, url: 'projects'}
- {title: Radio, url: 'radio'}
- {title: Contact, url: '#contact'}

#-------------------------------
# Menu Section

twitchbanner:
  username: mrdemonwolf
  apikey: n9zpqgrbidq5bujz49eilfkf2lvpnly

#-------------------------------
# SEO Section

seo:
  twitter-creator: '@mrdemonwolf'
  twitter-site: '@mrdemonwolf'
  type: 'website'

# google-analytics: UA-107275871-1

#-------------------------------
# About Section

about:
- Hi, I'm Nathan. I am a Frontend & UI Designer who has a passion for <strong>creating</strong> unique user <strong>experiences</strong>. Since 2012 I have been proudly making the internet a better place, one website at a time. I have had the pleasure to work on a variety of exciting projects involving <strong>WordPress</strong> development, <strong>UI design & front-end development</strong>.
- Currently I’m a contractor for <a href="https://kreynation.com"><strong>KreyNation</strong></a>. I’m also available for Freelance work for any exciting project with tech startups, businesses, entrepreneurs and developers all across the world to create stunning Interfaces and User Experiences. I look forward to hearing from you!

#-------------------------------
# Hero

hero-title: Nathan Henniges is a

hero:
- {name: Streamer}
- {name: YouTuber}
- {name: Front-end Developer}
- {name: UX Designer}
- {name: Gamer}

hero-button:
  title: Contact Me
  url: '#contact'

#-------------------------------
# Examples Section
example-header: Past Examples

# Max of 3
examples:
- {title: 'JSL Hub', url: 'jslhub', picture: 'jslhub.png', type: "work"}
- {title: 'Aishazart', url: 'aishazart', picture: 'aishazart.png', type: "work"}
- {title: 'Alan Crytex', url: 'alancrytex', picture: 'alancrytex.png', type: "work"}

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-spotify', color: 'spotify-color', url: 'https://open.spotify.com/user/demonwolf97/'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'http://www.twitter.com/mrdemonwolf'}
- {icon: 'fa-github', color: 'github-color', url: 'https://www.github.com/mrdemonwolf'}
- {icon: 'fa-youtube', color: 'youtube-color', url: 'https://www.youtube.com/mrdemonwolf'}
- {icon: 'fa-twitch', color: 'twitch-color', url: 'https://www.twitch.tv/mrdemonwolf/'}

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
