#-------------------------------
# General Site Settings

title: MrDemonWolf
name: MrDemonWolf
description: MrDemonWolf is UX Designer, Gamer, Streamer, Youtuber. Freelancer for UX Design and Wordpress site builds. Want a new website for your company or etc.
email: demonwolf@demonwolfdev.com
url: https://mrdemonwolf.me
# url: http://localhost:3001  #Dev URL

menu:
- {name: About, url: '#about'}
- {name: Work, url: '#work'}
- {name: Contact, url: '#contact'}

legal:
- {name: Privacy Statement, url: 'privacy-statement'}

#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/mrdemonwolf'
  type: 'website'

#-------------------------------
# Google Analytics Section

google-analytics-ua: UA-106544789-1

#-------------------------------
# About Section

about: >
  Hello my name is Nathan Henniges. Been fascinated with computers and design as the age of 13. I started working with websites around 2012. I learned a lot since then on how to better use the tools they have been given to me. I hope to work with UX Design in the future.

#-------------------------------
# Hero

hero:
- {name: Streamer}
- {name: YouTuber}
- {name: UX Designer}
- {name: Gamer}
#-------------------------------
# Work Section
# Make sure you put images in the /img/work/ folder.
work:
- {name: 'JSL Hub', picture: 'jslhub.jpg'}
- {name: 'Aishazart', picture: 'aishazart.jpg'}
#-------------------------------
# Contact Section

social:
- {icon: 'spotify', url: 'https://open.spotify.com/user/demonwolf97/'}
- {icon: 'twitter', url: 'http://www.twitter.com/mrdemonwolf'}
- {icon: 'github', url: 'https://www.github.com/mrdemonwolf'}
- {icon: 'youtube', url: 'https://www.youtube.com/mrdemonwolf'}
- {icon: 'twitch', url: 'https://www.twitch.tv/mrdemonwolf/'}