#-------------------------------
# General Site Settings
#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}
- {title: About, url: '#about'}
- {title: Projects, url: 'projects'}
- {title: Contact, url: '#contact'}

#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/mrdemonwolf'
  type: 'website'
  google-analytics: UA-107275871-1

#-------------------------------
# About Section

about: >
  Hello, my name is Nathan Henniges. Been fascinated with Technology and Front-end Development and UX Design. Started building and designing websites around 2012 with my very first community website. Learned how to use tools that have been given to me.  Front-end Development and UX Design is my passion.

#-------------------------------
# Hero
hero-title: Nathan Henniges
hero:
- {name: Streamer}
- {name: YouTuber}
- {name: UX Designer}
- {name: Gamer}

#-------------------------------
# Examples Section
# Make sure  put images in the /img/examples/ folder.
# Also a Max of 3
examples:
- {title: 'JSL Hub', url: 'jslhub', picture: 'jslhub.jpg'}
- {title: 'Aishazart', url: 'aishazart', picture: 'aishazart.jpg'}
- {title: 'Stream Team', url: 'stream_team', picture: 'stream_team.jpg'}

#-------------------------------
# Projects Gallery Section
# Filter
project_gallery-fliter:
- {title: 'All', name: 'all'}
- {title: 'Adobe XD', name: 'adobe-xd'}
- {title: 'HTML', name: 'html'}
- {title: 'Wordpress', name: 'wordpress'}

project_gallery-thumbnails:
#Make sure  put images in the /img/project/thumbnails folder.
- {title: 'JSL Hub', fliter: 'wordpress', picture: 'jslhub.jpg' , url: 'jslhub'}
- {title: 'Aishazart', fliter: 'wordpress', picture: 'aishazart.jpg', url: 'aishazart'}
- {title: 'Stream Team', fliter: 'adobe-xd', picture: 'stream_team.jpg', url: 'stream_team'}
- {title: 'Sushi Restaurant', fliter: 'adobe-xd', picture: 'sushi_restaurant.jpg', url: 'sushi_restaurant'}

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-spotify', color: 'spotify-color', url: 'https://open.spotify.com/user/demonwolf97/'}
- {icon: 'fa-twitter', color: 'twitter-color', url: 'http://www.twitter.com/mrdemonwolf'}
- {icon: 'fa-github', color: 'github-color', url: 'https://www.github.com/mrdemonwolf'}
- {icon: 'fa-youtube', color: 'youtube-color', url: 'https://www.youtube.com/mrdemonwolf'}
- {icon: 'fa-twitch', color: 'twitch-color', url: 'https://www.twitch.tv/mrdemonwolf/'}
social-url:
  spotify: https://open.spotify.com/user/demonwolf97
  twitter: http://www.twitter.com/mrdemonwolf
  github: https://www.github.com/mrdemonwolf
  youtube: https://www.youtube.com/mrdemonwolf
  twitch: https://www.twitch.tv/mrdemonwolf


#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
